### PR TITLE
try to get hold of swinject version to choose between Resolvable and …

### LINKED ISSUE #37: rename Resolvable to ResolverType when switching to Swinject 2.0.0.

### PR DESCRIPTION
**Pull request by Lutzifer**
…ResolverType - fixes #37

### CODE REVIEW

**Comment by yoichitgy** [comment]
Are we going to support Swinject v1 and v2 in a single version of Swinject-CodeGen? Changes on Swinject v2 are not only `ResolverType`. I'm not sure whether we should merge this change for now.

**Comment by ddengler** [comment]
@yoichitgy @Lutzifer  how about aligning the semantic versioning to swinject instead?

**Comment by Lutzifer** [comment]
if the changes in the generated code are larger, of course, we need to tackle this another way.

aligning the version is the way to go then imho, as @ddengler proposed

**Comment by yoichitgy** [comment]
@ddengler Yes, I was also thinking the alignment of the semantic version number.
@Lutzifer Let's postpone merging this PR to see whether the changes on Swinject v2 are large or not.

**Comment by Lutzifer** [comment]
closing this for now

**Pull request closed without merging**
