### PR TITLE
Make generated functions public

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by Lutzifer** [comment]
Thanks for the PR.
Does this actually have an effect on the code or is it just more precise?

**Comment by yoichitgy** [comment]
Thanks @swipesight for the PR😃, and thanks @Lutzifer for responding. Just FYI: Travis hasn't started for hours. I restarted it.

**Comment by Lutzifer** [comment]
this has become part of #65 , thank you

**Comment by davidkraus** [comment]
@swipesight is there any reason the functions have to be public?

Since swift 3 has a stricter access control this change has a large effect on the classes you inject.
Prefixing all methods with _public_ forces your classes to be (at least) _public_ as well. 

IMHO this is nothing a DI library should force you to do.

**Pull request closed without merging**
